services:
  xrootd-sdn-origin-1:
    image: ${SWARM}/xrootd-stageout-server:latest
    network_mode: host
    restart: unless-stopped
    hostname: sense-origin-01.ultralight.org
    environment:
    - X509_USER_PROXY=/etc/grid-security/x509
    - XRD_CERT=/etc/grid-security/xrootd/sense-origin-01/cert.pem
    - XRD_KEY=/etc/grid-security/xrootd/sense-origin-01/key.pem
    - XRD_REDIR=sense-redir-01.ultralight.org
    - XRD_PORT=1094
    - XRD_MNG_PORT=1213
    - LOCAL_ROOT=/storage/cms
    - SITENAME=T2_US_Caltech_SDN
    - XRD_INTF=macvlan1
    volumes:
    - ./config/default/etc/xrootd/scitokens.cfg:/etc/xrootd/scitokens.cfg:ro
    - ./config/default/etc/xrootd/lcmaps.db:/etc/xrootd/lcmaps.cfg:ro
    - ./config/default/etc/xrootd/robots.txt:/etc/xrootd/robots.txt:ro
    - /etc/xrootd/macaroon-secret:/etc/xrootd/macaroon-secret:ro
    - ./config/default/etc/xrootd/xrootd-clustered.cfg:/etc/xrootd/xrootd-clustered.cfg:ro
    - ./config/default/etc/xrootd/auth_file:/etc/xrootd/auth_file:ro
    - ./config/${HOSTNAME}/etc/xrootd/config.d:/etc/xrootd/config.d:ro
    - ./config/default/etc/supervisord.d/10-xrootd.conf:/etc/supervisord.d/10-xrootd.conf:ro
    - /etc/grid-security:/etc/grid-security:ro
    - /etc/passwd:/etc/passwd:ro
    - /etc/group:/etc/group:ro
    - /sdn-raid/T2_US_Caltech/:/storage/cms:rw
    cap_add:
    - CAP_SETUID
    - CAP_SETGID
    - CAP_DAC_OVERRIDE
  xrootd-sdn-origin-2:
    image: ${SWARM}/xrootd-stageout-server:latest
    network_mode: host
    hostname: sense-origin-02.ultralight.org
    environment:
    - X509_USER_PROXY=/etc/grid-security/x509
    - XRD_CERT=/etc/grid-security/xrootd/sense-origin-02/cert.pem
    - XRD_KEY=/etc/grid-security/xrootd/sense-origin-02/key.pem
    - XRD_REDIR=sense-redir-02.ultralight.org
    - XRD_PORT=1095
    - XRD_MNG_PORT=1214
    - LOCAL_ROOT=/storage/cms
    - SITENAME=T2_US_Caltech_SDN
    - XRD_INTF=macvlan2
    volumes:
    - ./config/default/etc/xrootd/scitokens.cfg:/etc/xrootd/scitokens.cfg:ro
    - ./config/default/etc/xrootd/lcmaps.db:/etc/xrootd/lcmaps.cfg:ro
    - ./config/default/etc/xrootd/robots.txt:/etc/xrootd/robots.txt:ro
    - /etc/xrootd/macaroon-secret:/etc/xrootd/macaroon-secret:ro
    - ./config/default/etc/xrootd/xrootd-clustered.cfg:/etc/xrootd/xrootd-clustered.cfg:ro
    - ./config/default/etc/xrootd/auth_file:/etc/xrootd/auth_file:ro
    - ./config/${HOSTNAME}/etc/xrootd/config.d:/etc/xrootd/config.d:ro
    - ./config/default/etc/supervisord.d/10-xrootd.conf:/etc/supervisord.d/10-xrootd.conf:ro
    - /etc/grid-security:/etc/grid-security:ro
    - /etc/passwd:/etc/passwd:ro
    - /etc/group:/etc/group:ro
    - /sdn-raid/T2_US_Caltech/:/storage/cms:rw
    cap_add:
    - CAP_SETUID
    - CAP_SETGID
    - CAP_DAC_OVERRIDE
  xrootd-sdn-origin-3:
    image: ${SWARM}/xrootd-stageout-server:latest
    network_mode: host
    hostname: sense-origin-03.ultralight.org
    environment:
    - X509_USER_PROXY=/etc/grid-security/x509
    - XRD_CERT=/etc/grid-security/xrootd/sense-origin-03/cert.pem
    - XRD_KEY=/etc/grid-security/xrootd/sense-origin-03/key.pem
    - XRD_REDIR=sense-redir-03.ultralight.org
    - XRD_PORT=1096
    - XRD_MNG_PORT=1215
    - LOCAL_ROOT=/storage/cms
    - SITENAME=T2_US_Caltech_SDN
    - XRD_INTF=macvlan3
    volumes:
    - ./config/default/etc/xrootd/scitokens.cfg:/etc/xrootd/scitokens.cfg:ro
    - ./config/default/etc/xrootd/lcmaps.db:/etc/xrootd/lcmaps.cfg:ro
    - ./config/default/etc/xrootd/robots.txt:/etc/xrootd/robots.txt:ro
    - /etc/xrootd/macaroon-secret:/etc/xrootd/macaroon-secret:ro
    - ./config/default/etc/xrootd/xrootd-clustered.cfg:/etc/xrootd/xrootd-clustered.cfg:ro
    - ./config/default/etc/xrootd/auth_file:/etc/xrootd/auth_file:ro
    - ./config/${HOSTNAME}/etc/xrootd/config.d:/etc/xrootd/config.d:ro
    - ./config/default/etc/supervisord.d/10-xrootd.conf:/etc/supervisord.d/10-xrootd.conf:ro
    - /etc/grid-security:/etc/grid-security:ro
    - /etc/passwd:/etc/passwd:ro
    - /etc/group:/etc/group:ro
    - /sdn-raid/T2_US_Caltech/:/storage/cms:rw
    cap_add:
    - CAP_SETUID
    - CAP_SETGID
    - CAP_DAC_OVERRIDE
