version: '3.8'
services:
  testpoint:
    image: perfsonar/testpoint:latest
    network_mode: "host"
    restart: on-failure
    volumes:
       - ./config/psconfig:/etc/perfsonar/psconfig
       - ./config/etc/httpd/conf/httpd.conf:/etc/httpd/conf/httpd.conf
       - ./config/etc/httpd/conf.d/ssl.conf:/etc/httpd/conf.d/ssl.conf
