services:
  xrootd-cache-mon-hdd:
    image: ${SWARM}/xrootd-clustered-server:latest
    network_mode: host
    restart: unless-stopped
    environment:
    - X509_USER_PROXY=/etc/grid-security/x509
    - REDIRECTOR=xcache.ultralight.org:2040
    volumes:
    - ./config/${HOSTNAME}/etc/t2_maitenance.conf:/etc/t2_maitenance.conf:ro
    - ./config/default/etc/supervisord.d/10-xrootd.conf:/etc/supervisord.d/10-xrootd.conf:ro
    - /etc/grid-security:/etc/grid-security:ro
    - /etc/passwd:/etc/passwd:ro
    - /etc/group:/etc/group:ro
    - /storage/cms/store/temp/user/jbalcas.cachetest/:/storage/cms/store/temp/user/jbalcas.cachetest/:rw
  xrootd-cache-mon-nvme:
    image: ${SWARM}/xrootd-clustered-server:latest
    network_mode: host
    restart: unless-stopped
    environment:
    - X509_USER_PROXY=/etc/grid-security/x509
    - REDIRECTOR=xcache-nvme.ultralight.org:1094
    volumes:
    - ./config/${HOSTNAME}/etc/t2_maitenance.conf:/etc/t2_maitenance.conf:ro
    - ./config/default/etc/supervisord.d/10-xrootd.conf:/etc/supervisord.d/10-xrootd.conf:ro
    - /etc/grid-security:/etc/grid-security:ro
    - /etc/passwd:/etc/passwd:ro
    - /etc/group:/etc/group:ro
    - /storage/cms/store/temp/user/jbalcas.cachetest/:/storage/cms/store/temp/user/jbalcas.cachetest/:rw
version: '2.4'
