services:
  xrootd-monitoring-shoveler:
    container_name: xrootd-monitoring-shoveler
    env_file:
    - docker-compose.env
    image: xrootd-monitoring-shoveler
    network_mode: host
    restart: unless-stopped
    build:
      context: .

