services:
  xrootd-clustered-server:
    image: ${SWARM}/xrootd-clustered-server:latest
    network_mode: host
    environment:
    - X509_USER_PROXY=/etc/grid-security/x509
    volumes:
    - ./config/default/etc/xrootd/scitokens.cfg:/etc/xrootd/scitokens.cfg:ro
    - ./config/default/etc/xrootd/lcmaps.db:/etc/xrootd/lcmaps.cfg:ro
    - ./config/default/etc/xrootd/macaroon-secret:/etc/xrootd/macaroon-secret:ro
    - ./config/default/etc/xrootd/xrootd.cfg:/etc/xrootd/xrootd.cfg:ro
    - ./config/default/etc/xrootd/auth_file:/etc/xrootd/auth_file:ro
    - ./config/${HOSTNAME}/etc/xrootd/config.d:/etc/xrootd/config.d:ro
    - ./config/default/etc/supervisord.d/10-xrootd.conf:/etc/supervisord.d/10-xrootd.conf:ro
    - /etc/grid-security:/etc/grid-security:ro
    - /etc/passwd:/etc/passwd:ro
    - /etc/group:/etc/group:ro
    - /storage/cms/:/storage/cms:ro
version: '2.4'
