services:
  xrootd-stageout-server:
    image: ${SWARM}/xrootd-stageout-server:latest
    network_mode: host
    restart: unless-stopped
    environment:
    - X509_USER_PROXY=/etc/grid-security/x509
    volumes:
    - /etc/xrootd/macaroon-secret:/etc/xrootd/macaroon-secret:ro
    - ./config/default/etc/xrootd/xrootd-clustered.cfg:/etc/xrootd/xrootd-clustered.cfg:ro
    - ./config/default/etc/xrootd/auth_file:/etc/xrootd/auth_file:ro
    - ./config/${HOSTNAME}/etc/xrootd/config.d:/etc/xrootd/config.d:ro
    - /etc/grid-security:/etc/grid-security:ro
    - /etc/passwd:/etc/passwd:ro
    - /etc/group:/etc/group:ro
    - /storage/cms/:/storage/cms:rw
    cap_add:
    - CAP_SETUID
    - CAP_SETGID
    - CAP_DAC_OVERRIDE
version: '2.4'
